In [15]:
import boto3
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score

## Defining the s3 bucket
s3 = boto3.resource('s3')
bucket_name = 'ryan-greiner-bucket'
bucket = s3.Bucket(bucket_name)

## Defining the file to be read from s3 bucket
file_key = 'CarPrice_Assignment.csv'
bucket_object = bucket.Object(file_key)
file_object = bucket_object.get()
file_content_stream = file_object.get('Body')

## Reading CSV file
price = pd.read_csv(file_content_stream)
price.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [16]:
X = price.drop(columns = ['price'], axis = 1)
Y = price['price']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

In [17]:
X_train_1 = X_train[['wheelbase', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']]
X_test_1 = X_test[['wheelbase', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']]
lm_md1 = LinearRegression().fit(X_train_1, Y_train)

lm_md1_pred = lm_md1.predict(X_test_1)
lm_md1_pred

mse1 = np.mean((Y_test - lm_md1_pred)**2)
print('The MSE of Model 1 is ', mse1)

The MSE of Model 1 is  16952578.263132095

In [20]:
X_train_2 = X_train[['carwidth', 'carheight', 'horsepower', 'citympg', 'highwaympg']]
X_test_2 = X_test[['carwidth', 'carheight', 'horsepower', 'citympg', 'highwaympg']]

lm_md2 = LinearRegression().fit(X_train_2, Y_train)

lm_md2_pred = lm_md1.predict(X_test_2)
lm_md2_pred

mse2 = np.mean((Y_test - lm_md2_pred)**2)
print('The MSE of Model 2 is ', mse2)

The MSE of Model 2 is  318498312.46336883

/home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages/sklearn/base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- carheight
- carwidth
Feature names seen at fit time, yet now missing:
- peakrpm
- wheelbase

  warnings.warn(message, FutureWarning)

In [ ]:
# MSE of model 1 is smaller so it is the prefered model